[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/healthcare/*"
  to = "/healthcare/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/healthcare/index.html"
  status = 200
