[build]
  command = "npm run build"
  publish = "build"

[[plugins]]
  package = "./netlify-build-plugin.js"

[[redirects]]
  from = "/healthcare/*"
  to = "/healthcare/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/healthcare/index.html"
  status = 200
