name: Deploy React App to EC2
on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies and build the React app
      - name: Install dependencies
        run: npm ci

      - name: Build the React app
        run: | 
          CI=false # remove this after fixing warnings 
          npm run build

      # Verify build output
      - name: Verify build
        run: |
          echo "Build directory contents:"
          ls -la build

      # Create SSH key file from secret (if needed)
      - name: Create SSH key file
        run: |
          echo "${{ secrets.KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      # Setup SSH config (optional but recommended)
      - name: Configure SSH
        run: |
          echo "Host ${{ secrets.HOST }}" > /home/runner/.ssh/config
          echo "  StrictHostKeyChecking no" >> /home/runner/.ssh/config

      # Copy build files to EC2
      - name: Copy build files to EC2
        run: |
          scp -i /home/runner/.ssh/id_rsa -r build/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/azureuser/server/healthcare_static_build/

      # Restart Express server on EC2
      - name: Restart Express server on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/azureuser/server/healthcare_static_build/
            ls -ll
