name: Deploy to Azure VM
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Start the build
        run: |
          CI=false # remove this after fixing warnings 
          npm run build
        
      - name: Verify build output
        run: |
          echo "Current directory: $(pwd)"
          echo "Build directory contents:"
          ls -la build
          
      - name: SCP files to VM
        run: |
          scp -i ${{ secrets.KEY }} -r build/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/azureuser/server/healthcare_static_build/build/
        
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "Current directory on VM: $(pwd)"
            cd /home/azureuser/server
            echo "Changed to directory: $(pwd)"
            
            # List contents after SCP
            echo "Contents of healthcare_static_build/build/:"
            ls -R healthcare_static_build/build/
            
            docker-compose down
            docker-compose build
            docker-compose up -d
            docker image prune -f
